### PR TITLE
Refactored

### PR DESCRIPTION
**Pull request by Aliyevvvg**

### CODE REVIEW

**Review by 0605AbMu — CHANGES_REQUESTED** [review]
Delete unneccessary codes

**Comment by Aliyevvvg** [comment]
refreshed

**Comment by Aliyevvvg** [comment]
Refreshed all to use

**Review by 0605AbMu — CHANGES_REQUESTED** [review]
Good job!

**Review by 0605AbMu — APPROVED** [review]

**Comment by Aliyevvvg** [comment]
@0605AbMu Confilict solved

**Review by 0605AbMu — APPROVED** [review]

**Pull request merged**
